# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=100)),
                ('Date', models.DateField(null=True)),
                ('Detail', models.TextField()),
                ('URL', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Concours_Collectivites_territoriales',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Collectivites_organisatrice', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=200)),
                ('Nombre_postes', models.IntegerField()),
                ('Delai_depot', models.DateField(blank=True, null=True)),
                ('Date_concours', models.DateField(blank=True, null=True)),
                ('Date_publication', models.DateField(blank=True, null=True)),
                ('CCPEE', models.TextField()),
                ('CCPEO', models.TextField()),
                ('Resultats', models.TextField()),
                ('Desistement', models.TextField()),
                ('PPI', models.TextField(null=True)),
                ('FA', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concours_Etablissements_Entreprises_publics',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Etablissement_organisateur', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=200)),
                ('Nombre_postes', models.IntegerField()),
                ('Delai_depot', models.DateField(blank=True, null=True)),
                ('Date_concours', models.DateField(blank=True, null=True)),
                ('Date_publication', models.DateField(blank=True, null=True)),
                ('CCPEE', models.TextField()),
                ('CCPEO', models.TextField()),
                ('Resultats', models.TextField()),
                ('Desistement', models.TextField()),
                ('PPI', models.TextField(null=True)),
                ('FA', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concours_Services_de_lEtat',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Administration_organisatrice', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=200)),
                ('Nombre_postes', models.IntegerField()),
                ('Delai_depot', models.DateField(blank=True, null=True)),
                ('Date_concours', models.DateField(blank=True, null=True)),
                ('Date_publication', models.DateField(blank=True, null=True)),
                ('CCPEE', models.TextField()),
                ('CCPEO', models.TextField()),
                ('Resultats', models.TextField()),
                ('Desistement', models.TextField()),
                ('PPI', models.TextField(null=True)),
                ('FA', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emplois_superieurs',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Emploi', models.CharField(max_length=100)),
                ('Autorite_Gouvernementale', models.TextField()),
                ('Arrete', models.TextField()),
                ('Date_limite', models.DateField(blank=True, null=True)),
                ('Date_publication', models.DateField(blank=True, null=True)),
                ('PPI', models.TextField(null=True)),
                ('FA', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postes_Etablissements_Entreprises_publics',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Etablissement_organisateur', models.TextField()),
                ('Poste', models.TextField()),
                ('Nombre_postes', models.IntegerField()),
                ('Date_de_depot', models.DateField(blank=True, null=True)),
                ('Date_publication', models.DateField(blank=True, null=True)),
                ('Candidats_convoques', models.TextField()),
                ('Resultats', models.TextField()),
                ('PPI', models.TextField(null=True)),
                ('FA', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postes_Provinces_et_prefectures',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Administration_organisatrice', models.TextField()),
                ('Nombre_postes_CD', models.IntegerField()),
                ('Nombre_postes_CS', models.IntegerField()),
                ('Date_de_depot', models.DateField(blank=True, null=True)),
                ('Date_publication', models.DateField(blank=True, null=True)),
                ('Candidats_convoques', models.TextField()),
                ('Resultats', models.TextField()),
                ('PPI', models.TextField(null=True)),
                ('FA', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postes_Services_de_lEtat',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Administration_organisatrice', models.TextField()),
                ('Nombre_postes_CD', models.IntegerField()),
                ('Nombre_postes_CS', models.IntegerField()),
                ('Date_de_depot', models.DateField(blank=True, null=True)),
                ('Date_publication', models.DateField(blank=True, null=True)),
                ('Candidats_convoques', models.TextField()),
                ('Resultats', models.TextField()),
                ('PPI', models.TextField(null=True)),
                ('FA', models.TextField(null=True)),
            ],
        ),
    ]
