# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cin', models.CharField(max_length=15)),
                ('Sexe', models.CharField(max_length=10)),
                ('Situation_fam', models.CharField(max_length=20)),
                ('Date_naissance', models.DateField(blank=True, null=True)),
                ('Adresse', models.TextField(blank=True)),
                ('Province', models.CharField(blank=True, max_length=20)),
                ('Email_confirmed', models.BooleanField(default=False)),
                ('Phone', models.IntegerField(blank=True)),
                ('Handicap', models.BooleanField(default=False)),
                ('Diplome', models.CharField(blank=True, max_length=100)),
                ('Specialites', models.CharField(blank=True, max_length=100)),
                ('Annee_obt', models.DateField(blank=True, null=True)),
                ('Langue1', models.CharField(blank=True, max_length=20)),
                ('Langue2', models.CharField(blank=True, max_length=20)),
                ('Langue3', models.CharField(blank=True, max_length=20)),
                ('Competences', models.TextField(blank=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
