# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Email_confirmed',
            new_name='email_confirmed',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Adresse',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Annee_obt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Cin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Competences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Date_naissance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Diplome',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Handicap',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Langue1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Langue2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Langue3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Province',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Sexe',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Situation_fam',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Specialites',
        ),
    ]
